### ISSUE TITLE
InvalidArgumentException on game startup

### ISSUE THREAD

**Issue by AngelWingsPanda** [Mica-Technologies/minecraft-city-super-mod#41]
This exception is immediately thrown after Minecraft is 65% loaded. I’m not sure what is causing this to happen, but we need to investigate.

**Comment by mica-alex** [comment]
```
[20:53:36] [Client thread/DEBUG] [FML]: Freezing registries
[20:53:36] [Client thread/WARN] [FML]: Registry Item: Override did not have an associated owner object. Name: csm:newesbrooksxarm1 Value: net.minecraft.item.ItemBlock@45566129
[20:53:36] [Client thread/WARN] [FML]: Registry Item: Override did not have an associated owner object. Name: csm:newesbrooksxarm1 Value: net.minecraft.item.ItemBlock@4c33ad71
[20:53:36] [Client thread/WARN] [FML]: Registry Item: Override did not have an associated owner object. Name: csm:teic Value: net.minecraft.item.ItemBlock@1a8cf1e4
[20:53:36] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:553]: ---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 10/4/23 8:53 PM
Description: Initializing game

java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:556)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:598)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:251)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.init(Minecraft.java:535)
	at net.minecraft.client.Minecraft.run(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.legacydev.Main.start(Main.java:86)
	at net.minecraftforge.legacydev.MainClient.main(MainClient.java:29)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:556)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:598)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:251)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.init(Minecraft.java:535)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.legacydev.Main.start(Main.java:86)
	at net.minecraftforge.legacydev.MainClient.main(MainClient.java:29)
```

**Comment by mica-alex** [comment]
Issued has been corrected. See linked commit.
